exclude: "docs|.git|test_*.py|__init__.py"
default_language_version:
  python: python3
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements 

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287
    hooks:
    -   id: ruff

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black