site_name: Melhor Envio SDK
repo_url: https://github.com/pliniomikael/melhorenvio-sdk
repo_name: pliniomikael/melhorenvio-sdk
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.footer
  icon:
    repo: fontawesome/brands/github

  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Trocar para dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Trocar para light mode



markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

plugins:
  - macros
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [melhorenvio]
          options:
            merge_init_into_class: true
            docstring_section_style: spacy
            separate_signature: false
            show_signature_annotations: true
            members_order: source

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pliniomikael
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/plinio-mikael-439a701a2/

